#!/usr/bin/env python3
"""
Blender BVH Importer Script
Imports BVH files generated by our exporter and creates proper armatures with animation.

Features:
- Imports BVH files with dynamic joint detection
- Creates armature with proper bone hierarchy
- Applies position and rotation data frame-by-frame
- Handles Z-up coordinate system alignment
- Sets up 30 FPS animation playback
- Prepares skeleton for MetaHuman retargeting

Usage:
- Run this script in Blender's Scripting tab
- Update BVH_FILE_PATH to point to your BVH file
- Execute the script to import and animate
"""

import bpy
import bmesh
import mathutils
from mathutils import Vector, Euler, Matrix
import os
import re

# Configuration
BVH_FILE_PATH = "output_full_joints.bvh"  # Update this path
ARMATURE_NAME = "BVH_Armature"
FRAME_RATE = 30
BONE_LENGTH = 0.1  # Default bone length in meters

class BVHJoint:
    """Represents a joint/bone in the BVH hierarchy"""
    def __init__(self, name, parent=None):
        self.name = name
        self.parent = parent
        self.children = []
        self.offset = Vector((0, 0, 0))
        self.channels = []
        self.channel_data = []  # Motion data for this joint
        
    def add_child(self, child):
        self.children.append(child)
        child.parent = self

class BVHParser:
    """Parses BVH files and extracts hierarchy and motion data"""
    
    def __init__(self, file_path):
        self.file_path = file_path
        self.root_joint = None
        self.joints = {}  # name -> BVHJoint mapping
        self.joint_list = []  # ordered list of joints
        self.frame_count = 0
        self.frame_time = 0.033333  # ~30 FPS
        self.motion_data = []
        
    def parse(self):
        """Parse the BVH file"""
        print(f"Parsing BVH file: {self.file_path}")
        
        if not os.path.exists(self.file_path):
            raise FileNotFoundError(f"BVH file not found: {self.file_path}")
        
        with open(self.file_path, 'r') as f:
            lines = [line.strip() for line in f.readlines()]
        
        # Find HIERARCHY and MOTION sections
        hierarchy_start = -1
        motion_start = -1
        
        for i, line in enumerate(lines):
            if line.startswith("HIERARCHY"):
                hierarchy_start = i
            elif line.startswith("MOTION"):
                motion_start = i
                break
        
        if hierarchy_start == -1 or motion_start == -1:
            raise ValueError("Invalid BVH file: missing HIERARCHY or MOTION section")
        
        # Parse hierarchy
        hierarchy_lines = lines[hierarchy_start:motion_start]
        self._parse_hierarchy(hierarchy_lines)
        
        # Parse motion
        motion_lines = lines[motion_start:]
        self._parse_motion(motion_lines)
        
        print(f"Parsed BVH: {len(self.joints)} joints, {self.frame_count} frames")
        
    def _parse_hierarchy(self, lines):
        """Parse the HIERARCHY section"""
        joint_stack = []
        current_joint = None
        
        for line in lines:
            line = line.strip()
            
            if line.startswith("ROOT") or line.startswith("JOINT"):
                # Extract joint name
                parts = line.split()
                joint_name = parts[1] if len(parts) > 1 else "Unknown"
                
                # Create joint
                parent = joint_stack[-1] if joint_stack else None
                joint = BVHJoint(joint_name, parent)
                
                if parent:
                    parent.add_child(joint)
                else:
                    self.root_joint = joint
                
                self.joints[joint_name] = joint
                self.joint_list.append(joint)
                joint_stack.append(joint)
                current_joint = joint
                
            elif line.startswith("OFFSET"):
                if current_joint:
                    parts = line.split()
                    if len(parts) >= 4:
                        offset = Vector((float(parts[1]), float(parts[2]), float(parts[3])))
                        current_joint.offset = offset
            
            elif line.startswith("CHANNELS"):
                if current_joint:
                    parts = line.split()
                    channel_count = int(parts[1])
                    channels = parts[2:2+channel_count]
                    current_joint.channels = channels
            
            elif line.startswith("End Site"):
                # End sites don't need special handling for our use case
                pass
                
            elif line == "}":
                if joint_stack:
                    joint_stack.pop()
    
    def _parse_motion(self, lines):
        """Parse the MOTION section"""
        frame_data_start = -1
        
        for i, line in enumerate(lines):
            if line.startswith("Frames:"):
                self.frame_count = int(line.split()[1])
            elif line.startswith("Frame Time:"):
                self.frame_time = float(line.split()[2])
            elif line and not line.startswith("MOTION") and not line.startswith("Frames") and not line.startswith("Frame"):
                frame_data_start = i
                break
        
        if frame_data_start == -1:
            print("Warning: No motion data found")
            return
        
        # Parse frame data
        for line in lines[frame_data_start:]:
            if line.strip():
                values = [float(x) for x in line.split()]
                self.motion_data.append(values)
        
        print(f"Loaded {len(self.motion_data)} frames of motion data")

class BlenderBVHImporter:
    """Imports BVH data into Blender and creates animated armature"""
    
    def __init__(self, bvh_parser):
        self.bvh = bvh_parser
        self.armature_obj = None
        self.armature_data = None
        
    def import_to_blender(self):
        """Main import function"""
        print("Importing BVH to Blender...")
        
        # Clear existing objects (optional)
        self._clear_scene()
        
        # Set up scene
        self._setup_scene()
        
        # Create armature
        self._create_armature()
        
        # Apply motion data
        self._apply_motion_data()
        
        # Finalize
        self._finalize_import()
        
        print("BVH import completed successfully!")
    
    def _clear_scene(self):
        """Clear existing objects (optional - be careful!)"""
        # Uncomment the following lines if you want to clear the scene
        # bpy.ops.object.select_all(action='SELECT')
        # bpy.ops.object.delete(use_global=False)
        pass
    
    def _setup_scene(self):
        """Set up scene settings"""
        scene = bpy.context.scene
        
        # Set frame rate
        scene.render.fps = FRAME_RATE
        scene.render.fps_base = 1.0
        
        # Set frame range
        scene.frame_start = 1
        scene.frame_end = self.bvh.frame_count
        scene.frame_current = 1
        
        print(f"Scene setup: {FRAME_RATE} FPS, {self.bvh.frame_count} frames")
    
    def _create_armature(self):
        """Create armature with bones matching BVH hierarchy"""
        # Create armature data
        armature_data = bpy.data.armatures.new(name=ARMATURE_NAME)
        armature_data.display_type = 'STICK'
        
        # Create armature object
        armature_obj = bpy.data.objects.new(ARMATURE_NAME, armature_data)
        bpy.context.collection.objects.link(armature_obj)
        
        # Set as active and enter edit mode
        bpy.context.view_layer.objects.active = armature_obj
        bpy.ops.object.mode_set(mode='EDIT')
        
        # Create bones
        self._create_bones_recursive(self.bvh.root_joint, Vector((0, 0, 0)))
        
        # Return to object mode
        bpy.ops.object.mode_set(mode='OBJECT')
        
        self.armature_obj = armature_obj
        self.armature_data = armature_data
        
        print(f"Created armature with {len(armature_data.bones)} bones")
    
    def _create_bones_recursive(self, joint, parent_tail):
        """Recursively create bones for the joint hierarchy"""
        if not joint:
            return
        
        # Calculate bone head and tail positions
        bone_head = parent_tail + joint.offset
        
        # For tail position, use child offset or default length
        if joint.children:
            # Use the first child's position as reference
            bone_tail = bone_head + joint.children[0].offset
        else:
            # End bone - use default length
            bone_tail = bone_head + Vector((0, BONE_LENGTH, 0))
        
        # Create bone
        bone = self.armature_data.edit_bones.new(joint.name)
        bone.head = bone_head
        bone.tail = bone_tail
        
        # Set parent relationship
        if joint.parent:
            parent_bone = self.armature_data.edit_bones.get(joint.parent.name)
            if parent_bone:
                bone.parent = parent_bone
        
        # Create child bones
        for child in joint.children:
            self._create_bones_recursive(child, bone_tail)
    
    def _apply_motion_data(self):
        """Apply motion data to bones frame by frame"""
        if not self.motion_data:
            print("No motion data to apply")
            return
        
        print("Applying motion data...")
        
        # Enter pose mode
        bpy.context.view_layer.objects.active = self.armature_obj
        bpy.ops.object.mode_set(mode='POSE')
        
        # Clear existing animation data
        if self.armature_obj.animation_data:
            self.armature_obj.animation_data_clear()
        
        # Apply data frame by frame
        for frame_idx, frame_data in enumerate(self.bvh.motion_data):
            frame_num = frame_idx + 1
            bpy.context.scene.frame_set(frame_num)
            
            self._apply_frame_data(frame_data)
            
            # Insert keyframes for all pose bones
            for pose_bone in self.armature_obj.pose.bones:
                pose_bone.keyframe_insert(data_path="location", group=pose_bone.name)
                pose_bone.keyframe_insert(data_path="rotation_euler", group=pose_bone.name)
        
        # Return to object mode
        bpy.ops.object.mode_set(mode='OBJECT')
        
        print(f"Applied motion data for {len(self.bvh.motion_data)} frames")
    
    def _apply_frame_data(self, frame_data):
        """Apply single frame of motion data"""
        data_index = 0
        
        for joint in self.bvh.joint_list:
            pose_bone = self.armature_obj.pose.bones.get(joint.name)
            if not pose_bone:
                continue
            
            # Reset transforms
            pose_bone.location = Vector((0, 0, 0))
            pose_bone.rotation_euler = Euler((0, 0, 0), 'XYZ')
            
            # Apply channel data
            for channel in joint.channels:
                if data_index >= len(frame_data):
                    break
                
                value = frame_data[data_index]
                data_index += 1
                
                if channel == "Xposition":
                    pose_bone.location.x = value
                elif channel == "Yposition":
                    pose_bone.location.y = value
                elif channel == "Zposition":
                    pose_bone.location.z = value
                elif channel == "Xrotation":
                    pose_bone.rotation_euler.x = math.radians(value)
                elif channel == "Yrotation":
                    pose_bone.rotation_euler.y = math.radians(value)
                elif channel == "Zrotation":
                    pose_bone.rotation_euler.z = math.radians(value)
    
    def _finalize_import(self):
        """Finalize the import process"""
        # Set interpolation mode for smoother animation
        if self.armature_obj.animation_data and self.armature_obj.animation_data.action:
            for fcurve in self.armature_obj.animation_data.action.fcurves:
                for keyframe in fcurve.keyframe_points:
                    keyframe.interpolation = 'LINEAR'
        
        # Set timeline to first frame
        bpy.context.scene.frame_set(1)
        
        # Select the armature
        bpy.ops.object.select_all(action='DESELECT')
        self.armature_obj.select_set(True)
        bpy.context.view_layer.objects.active = self.armature_obj

def main():
    """Main execution function"""
    import math  # Import math for radians conversion
    
    print("=== Blender BVH Importer ===")
    
    # Get the directory where this script is located
    script_dir = os.path.dirname(os.path.abspath(__file__))
    bvh_path = os.path.join(script_dir, BVH_FILE_PATH)
    
    # If the file doesn't exist in script directory, try current working directory
    if not os.path.exists(bvh_path):
        bvh_path = BVH_FILE_PATH
        
    try:
        # Parse BVH file
        parser = BVHParser(bvh_path)
        parser.parse()
        
        # Import to Blender
        importer = BlenderBVHImporter(parser)
        importer.import_to_blender()
        
        print("✓ BVH import successful!")
        print(f"✓ Created armature: {ARMATURE_NAME}")
        print(f"✓ Animation: {parser.frame_count} frames at {FRAME_RATE} FPS")
        print("✓ Ready for MetaHuman retargeting")
        print("\nTo play animation: Press Spacebar or click Play button")
        
    except Exception as e:
        print(f"❌ Error importing BVH: {e}")
        import traceback
        traceback.print_exc()

# Execute the script
if __name__ == "__main__":
    main()
else:
    # If running in Blender, execute directly
    main()